### ISSUE TITLE
Finetuning with VOC2007

### ISSUE THREAD

**Issue by Asif6511** [adityaarun1/Detectron.pytorch#5]
Hi! 

I trained from scratch completely a network with COCO2017 dataset with:

python tools/train_net_step.py --dataset coco2017 --cfg configs/baselines/e2e_mask_rcnn_R-50-FPN_1x.yaml --use_tfboard --bs=2

I now used the checkpoint (pth file) created from the train from scratch to finetune with VOC2007 dataset.

As expected I ran into trouble because the number of classes in VOC (21) and COCO (81) are different. I understand its possible to finetune as there are steps given to finetune custom dataset with different number of classes. I would like to know how to do this?

The command i used:
python tools/train_net_step.py --dataset voc2007 --cfg configs/baselines/e2e_mask_rcnn_R-50-FPN_1x.yaml --load_ckpt=/home/deep/data/asif/Detectron/Detectron.pytorch/Outputs/e2e_mask_rcnn_R-50-FPN_1x/Mar14-14-59-32_deeppc_step/ckpt/model_step719999.pth --use_tfboard --bs=2

The errors I got:
Traceback (most recent call last):
  File "tools/train_net_step.py", line 471, in <module>
    main()
  File "tools/train_net_step.py", line 331, in main
    net_utils.load_ckpt(maskRCNN, checkpoint['model'])
  File "/home/deep/data/asif/Detectron/Detectron.pytorch/lib/utils/net.py", line 163, in load_ckpt
    model.load_state_dict(state_dict, strict=False)
  File "/home/deep/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generalized_RCNN:
        size mismatch for Box_Outs.cls_score.weight: copying a param with shape torch.Size([81, 1024]) from checkpoint, the shape in current model is torch.Size([21, 1024]).
        size mismatch for Box_Outs.cls_score.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([21]).
        size mismatch for Box_Outs.bbox_pred.weight: copying a param with shape torch.Size([324, 1024]) from checkpoint, the shape in current model is torch.Size([84, 1024]).
        size mismatch for Box_Outs.bbox_pred.bias: copying a param with shape torch.Size([324]) from checkpoint, the shape in current model is torch.Size([84]).
        size mismatch for Mask_Outs.classify.weight: copying a param with shape torch.Size([81, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([21, 256, 1, 1]).
        size mismatch for Mask_Outs.classify.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([21]).

**Comment by adityaarun1** [comment]
Hi, You need to run the model only on VOC 2007 and not on COCO. It seems you are running the training script on COCO first. You need not pretrain the VOC2007 model over COCO. Here are the following steps:

1. Clone the repo: `git clone https://github.com/roytseng-tw/mask-rcnn.pytorch.git`
2. Compile the custom cuda layers: `cd lib` and then `sh make.sh`
3. Data preperation: `cd {repo root}` and then `mkdir data`. After this you need to simlink VOC dataset as instructed in [here](https://github.com/adityaarun1/Detectron.pytorch#data-preparation) (Subsection PASCAL VOC 2007 + 12).
4. You then need to download Imagenet pretrained weights from Caffe for the particular backbone network and put them in `{repo_root}/data/pretrained_model`. A helper command to download them all is `python tools/download_imagenet_weights.py`. Alternatively, you can also download weights given by the detectron models as mentioned in the README.
5.  After this, you need to kick off the training for VOC07 dataset with `python tools/train_net_step.py --dataset voc2007 --cfg configs/baselines/e2e_faster_rcnn_R-101-FPN_1x.yaml --use_tfboard --bs {batch_size} --nw {num_workers}`. Note the `--dataset voc2007` option specified here instead of `coco2017`!

**Comment by Asif6511** [comment]
Hey! I am considering the VOC2007 as a custom dataset. I am trying to implement the finetuning with custom dataset section using the pretrained model in COCO.

**Comment by adityaarun1** [comment]
Oh! I see. So instead of completely training on your custom dataset from scratch, you want to fine tune on your custom data. In that case, the simplest approach would be to initialize your model corresponding to your custom dataset (i.e. the number of classes equal to the number of classes in your dataset) and then load the pre-trained COCO model for all layers except the last layer for the detection, classification (and/or mask/keypoint) branch. Moreover, for fine-tuning, you will need to adjust the learning rates of different layers accordingly.

**Comment by Asif6511** [comment]
Yes! that is what I would like to do! Can you please help me with the steps to achieve this?
1. I am not sure where I can set the number of classes in model equal to that of the dataset!
2. How to load a pretrained model only for layers other than the output layer?

I cannot find the necessary steps in the Detectron repo as well. So, any Help would be helpful!

**Comment by Asif6511** [comment]
Hey,

I believe for setting the number of classes, I can just specify in the config file using MODEL.NUM_CLASSES =21. I hope this works. What can I do to load pretrained model with layers other than the output layer?

**Comment by adityaarun1** [comment]
Hi,

You can delete the last layer (or the necessary layers in case of `mask` branch) from the respective branches (`detection`, `classification`, `mask/keypoint`) when you load the pre-trained COCO checkpoint [here](https://github.com/adityaarun1/Detectron.pytorch/blob/master/tools/train_net.py#L271). The model definition and everything else should remain as per your dataset (i.e. the number of classes, the learning rate of various layers and so on). You should also use the argument `--load_ckpt` when training on your data and point it to the pretrained COCO data.

Let me know if this helps/works.

**Comment by Asif6511** [comment]
Hi! I made changes exactly in the line you have mentioned. I borrowed ideas from this script to implement here [https://gist.github.com/wangg12/aea194aa6ab6a4de088f14ee193fd968](url)
And now it works fine! 
Thanks for your help.

**Comment by Asif6511** [comment]
@adityaarun1 You mentioned in our conversation to change the learning rates in each layers accordingly! Any particular reason why? And can I just explicitly mention it in the config file?

**Comment by adityaarun1** [comment]
Yes, you should consider changing the learning rates. As you are already fine-tuning on a pre-trained COCO model, except for the last layer, all of the layers (backbone layers, RPN, detection head, mask head, keypoint head etc.) are already trained and are near their local optimum. So you would only want a higher learning rate only for the last layer and maybe want a very small learning rate for the rest of the preceding layers. 

I don't think that just modifying configuration files will do that. If you consider freezing all the previous layers (backbone layers, RPN) then you can exclude those layers [here](https://github.com/adityaarun1/Detectron.pytorch/blob/master/tools/train_net.py#L253-L260), or have different learning rates for the two sets of parameters in the optimizer.

**Comment by Asif6511** [comment]
Thanks for the Input @adityaarun1 ! I will close this issue now!
